name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Code
        run: make setup-test

      - name: Run tests
        run: make test

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          file: cobertura.xml
