name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v12
        with:
          name: garden-gateway
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run tests
        run: nix-shell --run "make test"
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          file: cobertura.xml
